name: 9
timestamp: 1445315631
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1444428972
positions:
  header: Header
  breadcrumbs: Breadcrumbs
  footer: Footer
