preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1444428972
children:
  -
    id: b6977fc1-a851-aabc-e524-a618fb2f91bc
    type: section
    subtype: false
    title: Header
    attributes:
      boxed: 0
    children:
      -
        id: aca90411-d382-991c-a28e-3a82abbf55e4
        type: grid
        subtype: false
        title: Untitled
        attributes: {  }
        children:
          -
            id: dd67f9c3-cfb8-d69c-7097-838bb1b11e27
            type: block
            subtype: false
            title: Untitled
            attributes:
              size: 30
            children:
              -
                id: 6a960439-dcbd-2913-9f9e-e0f2bab69351
                type: particle
                subtype: logo
                title: Logo
                attributes:
                  enabled: 1
                children: {  }
          -
            id: b2bd76f2-56dd-0640-d53c-7578863b2cc7
            type: block
            subtype: false
            title: Untitled
            attributes:
              size: 70
            children:
              -
                id: 3f030e88-933c-5d90-9c0f-6a02fc459742
                type: position
                subtype: false
                title: Header
                attributes:
                  enabled: 1
                  key: header
                  title: Header
                children: {  }
  -
    id: 7214b7d2-7a92-0758-b31a-e7d1e3d365fb
    type: section
    subtype: false
    title: Navigation
    attributes:
      boxed: 0
    children:
      -
        id: dc5f1269-77ff-277e-04da-000ecba4e808
        type: grid
        subtype: false
        title: Untitled
        attributes: {  }
        children:
          -
            id: 0180d064-c702-5401-f273-a1802c0c71e3
            type: block
            subtype: false
            title: Untitled
            attributes:
              variations: align-right
              extra: {  }
              fixed: '0'
              size: 100
            children:
              -
                id: bb13d9b7-4a41-6275-1cbf-82b8259182b3
                type: particle
                subtype: menu
                title: Menu
                attributes:
                  enabled: 1
                children: {  }
  -
    id: 0981e0f7-db45-9aa8-8587-4acc95868c0b
    type: section
    subtype: false
    title: Main
    attributes:
      boxed: 0
    children:
      -
        id: c2089732-c4d9-5048-ad10-6fc03c80c275
        type: grid
        subtype: false
        title: Untitled
        attributes: {  }
        children:
          -
            id: e8a69ab4-a902-ab0e-0ace-c9f94a40c468
            type: block
            subtype: false
            title: Untitled
            attributes:
              size: 100
            children:
              -
                id: 20521c9c-815b-7a3a-5f6a-7f368682f5ff
                type: position
                subtype: false
                title: Breadcrumbs
                attributes:
                  enabled: 1
                  key: breadcrumbs
                  title: Breadcrumbs
                children: {  }
      -
        id: 21281ad6-ba69-d2d3-6c01-6ff2e5f812f3
        type: grid
        subtype: false
        title: Untitled
        attributes: {  }
        children:
          -
            id: 093532dc-90b7-2099-1122-773e39a6c095
            type: block
            subtype: false
            title: Untitled
            attributes:
              size: 100
            children:
              -
                id: 1c9dd2ee-27a4-ca07-0943-0f8f11189f28
                type: pagecontent
                subtype: system-messages
                title: 'System Messages'
                attributes:
                  enabled: 1
                children: {  }
      -
        id: f02ff55f-824c-b761-014a-ccee0dbb1a46
        type: grid
        subtype: false
        title: Untitled
        attributes: {  }
        children:
          -
            id: 973b41d7-cbb9-936f-8665-246c7c2f852d
            type: block
            subtype: false
            title: Untitled
            attributes:
              size: 100
            children:
              -
                id: 00caf120-f69f-b116-948e-b9ef7f3f6bde
                type: pagecontent
                subtype: false
                title: Pagecontent
                attributes:
                  enabled: 1
                children: {  }
  -
    id: 81de5aea-531c-f197-55ff-ca9fc27ef9f6
    type: section
    subtype: false
    title: Footer
    attributes:
      boxed: 0
    children:
      -
        id: 8b07681f-d3d9-d579-c850-57a910c675a2
        type: grid
        subtype: false
        title: Untitled
        attributes: {  }
        children:
          -
            id: c61de004-1d44-aff9-b4c4-afab1cb73cf5
            type: block
            subtype: false
            title: Untitled
            attributes:
              size: 100
            children:
              -
                id: 70df6ac5-86e5-3e9b-0e31-24fdc259a80e
                type: position
                subtype: false
                title: Footer
                attributes:
                  enabled: 1
                  key: footer
                  title: Footer
                children: {  }
      -
        id: e49e50e8-697c-b4f4-0fd8-7c6b3eeb0d0a
        type: grid
        subtype: false
        title: Untitled
        attributes: {  }
        children:
          -
            id: 129195d6-f17f-dc87-75e4-fd74578ac936
            type: block
            subtype: false
            title: Untitled
            attributes:
              size: 40
            children:
              -
                id: 174af426-bab7-b6f2-6ef7-cbf1b29ad7bf
                type: particle
                subtype: copyright
                title: Copyright
                attributes:
                  enabled: 1
                children: {  }
          -
            id: 0e21da40-91a4-0581-0edc-9da9b49af222
            type: block
            subtype: false
            title: Untitled
            attributes:
              size: 30
            children:
              -
                id: f7b15198-5c2c-36f8-4ffe-2ad1dcd1acd1
                type: spacer
                subtype: false
                title: Spacer
                attributes:
                  enabled: 1
                children: {  }
          -
            id: 52af6dd6-ae95-f371-e80c-5bc3ed03870f
            type: block
            subtype: false
            title: Untitled
            attributes:
              size: 30
            children:
              -
                id: e97196d7-d9f9-8cf2-1af6-631b0efd1e27
                type: particle
                subtype: branding
                title: Branding
                attributes:
                  enabled: 1
                children: {  }
  -
    id: 793366c7-ae50-4f0a-38e4-2f7482846cf2
    type: offcanvas
    subtype: false
    title: Offcanvas
    attributes:
      name: 'Offcanvas Section'
      boxed: 0
    children:
      -
        id: 65831d0b-f3ad-f2a3-458f-f80e4fe4dd5c
        type: grid
        subtype: false
        title: Untitled
        attributes: {  }
        children:
          -
            id: 8c505d27-2d01-1ba0-f46a-034b29b31222
            type: block
            subtype: false
            title: Untitled
            attributes:
              size: 100
            children:
              -
                id: 9cc123e2-0711-743f-b115-5867553fe7ba
                type: particle
                subtype: mobile-menu
                title: Mobile-menu
                attributes:
                  enabled: 1
                children: {  }
  -
    id: 69722dd2-65aa-c20d-c2a5-e8f2b09bec51
    type: atoms
    subtype: false
    title: Atoms
    attributes:
      name: 'Atoms Section'
      boxed: 0
    children:
      -
        id: b6070a66-4d82-4c9e-8c1a-26cb8c82ff0a
        type: grid
        subtype: false
        title: Untitled
        attributes: {  }
        children: {  }
