preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1444428972
children:
  -
    id: 339bcc72-92e6-ac9d-b40f-10cb53cb4868
    type: section
    subtype: false
    title: Header
    attributes:
      boxed: 0
    children: {  }
  -
    id: 57169c33-4072-55fc-4df4-56c897f6149b
    type: section
    subtype: false
    title: Navigation
    attributes:
      boxed: 0
    children:
      -
        id: 73a5a6a8-e88b-7735-3b1c-b8c70cea3d52
        type: grid
        subtype: false
        title: Untitled
        attributes: {  }
        children:
          -
            id: 78d81f6d-1f22-1f3d-c69e-953e756b4013
            type: block
            subtype: false
            title: Untitled
            attributes:
              size: 100
              variations: align-right
              extra: {  }
              fixed: '0'
            children:
              -
                id: 476d6f39-50fd-187c-b078-d08e968ca267
                type: particle
                subtype: menu
                title: Menu
                attributes:
                  enabled: 1
                children: {  }
  -
    id: 06f64ad4-7385-4fc4-ebc5-db2e4c47cb0f
    type: section
    subtype: false
    title: Main
    attributes:
      boxed: 0
    children:
      -
        id: 5ce13316-fe33-412b-1c88-b70db7999ab4
        type: grid
        subtype: false
        title: Untitled
        attributes: {  }
        children:
          -
            id: 5891ba0a-5f9b-c59c-6d92-1ac69f5e9993
            type: block
            subtype: false
            title: Untitled
            attributes:
              size: 100
            children:
              -
                id: 333bacff-946e-310c-6fa8-7a2a3f76ebcc
                type: pagecontent
                subtype: system-messages
                title: 'System Messages'
                attributes:
                  enabled: 1
                children: {  }
      -
        id: 70b03297-d0a3-1350-a5d2-2ee8ba713243
        type: grid
        subtype: false
        title: Untitled
        attributes: {  }
        children:
          -
            id: 2cc83e34-6e0b-47c9-908c-b55ede9df300
            type: block
            subtype: false
            title: Untitled
            attributes:
              size: 30
              extra: {  }
              fixed: '0'
            children:
              -
                id: b242b3f2-635f-4a13-ae5f-9c30268651bf
                type: position
                subtype: module
                title: 'Module Instance'
                attributes:
                  enabled: 1
                  module_id: '16'
                  title: 'Module Instance'
                  key: module-instance
                children: {  }
          -
            id: 010fc1f5-7428-f114-ecf4-8d78ddcdadaf
            type: block
            subtype: false
            title: Untitled
            attributes:
              size: 70
            children:
              -
                id: 1751f9a3-e17a-f949-1924-b128d88d522e
                type: pagecontent
                subtype: false
                title: Pagecontent
                attributes:
                  enabled: 1
                children: {  }
  -
    id: 3f1948a3-79b8-92a0-8069-31546c889096
    type: section
    subtype: false
    title: Footer
    attributes:
      boxed: 0
    children:
      -
        id: 76a61db6-cd91-3439-a5fa-826fef88577a
        type: grid
        subtype: false
        title: Untitled
        attributes: {  }
        children:
          -
            id: 94df770a-e290-90c9-404b-da18a7d4ad0a
            type: block
            subtype: false
            title: Untitled
            attributes:
              size: 100
            children:
              -
                id: 8438c298-0f98-ab26-bd34-785848babc83
                type: position
                subtype: false
                title: Footer
                attributes:
                  enabled: 1
                  key: footer
                  title: Footer
                children: {  }
      -
        id: 9160697a-7aeb-7fe4-5b05-6ae9a3f6a00c
        type: grid
        subtype: false
        title: Untitled
        attributes: {  }
        children:
          -
            id: 06366535-3fe8-8156-6c9d-95bea575426d
            type: block
            subtype: false
            title: Untitled
            attributes:
              size: 40
            children:
              -
                id: bdf9d583-c34d-0f7d-0511-a5f33921ba35
                type: particle
                subtype: copyright
                title: Copyright
                attributes:
                  enabled: 1
                children: {  }
          -
            id: c423dd66-d7c3-4bb7-657f-6afdacdacef1
            type: block
            subtype: false
            title: Untitled
            attributes:
              size: 30
            children:
              -
                id: 7067908b-6a57-8979-2727-54893b46039f
                type: spacer
                subtype: false
                title: Spacer
                attributes:
                  enabled: 1
                children: {  }
          -
            id: 565e63da-f22c-cd27-5a95-e523e7f79e43
            type: block
            subtype: false
            title: Untitled
            attributes:
              size: 30
            children:
              -
                id: deb257d8-d81e-f7d1-20c6-cb0d663466de
                type: particle
                subtype: branding
                title: Branding
                attributes:
                  enabled: 1
                children: {  }
  -
    id: 4c6ccf50-fb8d-ec71-ed63-d728ff0fa91f
    type: offcanvas
    subtype: false
    title: Offcanvas
    attributes:
      name: 'Offcanvas Section'
      boxed: 0
    children:
      -
        id: d5d87d23-a1c3-1145-5313-a6cf53589931
        type: grid
        subtype: false
        title: Untitled
        attributes: {  }
        children:
          -
            id: 650345fb-7e01-7ff4-f42a-467727b6ce94
            type: block
            subtype: false
            title: Untitled
            attributes:
              size: 100
            children:
              -
                id: af70d8ea-c769-4ffa-ed31-9533294b0935
                type: particle
                subtype: mobile-menu
                title: Mobile-menu
                attributes:
                  enabled: 1
                children: {  }
  -
    id: 96a03d6a-9fa6-3785-868a-575b496c9600
    type: atoms
    subtype: false
    title: Atoms
    attributes:
      name: 'Atoms Section'
      boxed: 0
    children:
      -
        id: 5300f38b-2208-4e82-b812-8d18a366b47a
        type: grid
        subtype: false
        title: Untitled
        attributes: {  }
        children: {  }
