preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1444428972
children:
  -
    id: 69a187a0-9cff-23e6-6b4c-6b856828bee0
    type: section
    subtype: false
    title: Header
    attributes:
      boxed: 0
    children: {  }
  -
    id: 65a3964a-4d85-a943-a95f-6d0c0608db6b
    type: section
    subtype: false
    title: Navigation
    attributes:
      boxed: 0
    children:
      -
        id: b4ea1ae9-9672-9161-220f-ff67985ddcb1
        type: grid
        subtype: false
        title: Untitled
        attributes: {  }
        children:
          -
            id: ba90452d-3b47-549d-86c8-c78b1ed902e0
            type: block
            subtype: false
            title: Untitled
            attributes:
              size: 100
              variations: align-right
              extra: {  }
              fixed: '0'
            children:
              -
                id: abab13f0-ca02-f5c6-21fa-0513038e1ee5
                type: particle
                subtype: menu
                title: Menu
                attributes:
                  enabled: 1
                children: {  }
  -
    id: 5b5bbbcd-cd4a-0a1f-0e34-aca9963e8793
    type: section
    subtype: false
    title: Main
    attributes:
      boxed: 0
    children:
      -
        id: d8c8ed57-31c4-f8ed-6a13-6125b95e1dfc
        type: grid
        subtype: false
        title: Untitled
        attributes: {  }
        children:
          -
            id: 652c47d8-7e73-70cb-9db0-96badbb08a1f
            type: block
            subtype: false
            title: Untitled
            attributes:
              size: 100
            children:
              -
                id: 9fada2a0-765b-81b3-f7c0-9cad8a1ea30b
                type: position
                subtype: false
                title: Breadcrumbs
                attributes:
                  enabled: 1
                  key: breadcrumbs
                  title: Breadcrumbs
                children: {  }
      -
        id: 55704750-ddd5-c3f1-368c-160fc924fca7
        type: grid
        subtype: false
        title: Untitled
        attributes: {  }
        children:
          -
            id: 437a4923-ed1e-3dea-9a35-632c522179ac
            type: block
            subtype: false
            title: Untitled
            attributes:
              size: 100
            children:
              -
                id: 8faaae33-f719-44ff-76e8-36688db6c598
                type: pagecontent
                subtype: system-messages
                title: 'System Messages'
                attributes:
                  enabled: 1
                children: {  }
      -
        id: 8c2520d5-6f3b-df23-cd84-3d3d93d9a8c3
        type: grid
        subtype: false
        title: Untitled
        attributes: {  }
        children:
          -
            id: d1aa0ad7-48f3-be8c-2799-cc62bc26014f
            type: block
            subtype: false
            title: Untitled
            attributes:
              size: 100
            children:
              -
                id: 365026fd-e83b-bc5e-c244-8b53b4027717
                type: pagecontent
                subtype: false
                title: Pagecontent
                attributes:
                  enabled: 1
                children: {  }
  -
    id: 38afd55c-4ca7-228f-c288-5087683aa48d
    type: section
    subtype: false
    title: Footer
    attributes:
      boxed: 0
    children:
      -
        id: a606aeb2-531f-7770-d48c-62d0268e6e8a
        type: grid
        subtype: false
        title: Untitled
        attributes: {  }
        children:
          -
            id: 06e91ae4-11ba-2cf6-1196-9abc398eba31
            type: block
            subtype: false
            title: Untitled
            attributes:
              size: 100
            children:
              -
                id: 45c3a43f-e2b1-02e2-7254-0496e2307d9b
                type: position
                subtype: false
                title: Footer
                attributes:
                  enabled: 1
                  key: footer
                  title: Footer
                children: {  }
      -
        id: a539fb93-281c-577c-c559-f5cfc17d743c
        type: grid
        subtype: false
        title: Untitled
        attributes: {  }
        children:
          -
            id: 90d9a60e-ded0-79c8-5eee-55e134850b4b
            type: block
            subtype: false
            title: Untitled
            attributes:
              size: 40
            children:
              -
                id: 5b16f7cd-6b68-8d43-c42a-77900ebe9c4a
                type: particle
                subtype: copyright
                title: Copyright
                attributes:
                  enabled: 1
                children: {  }
          -
            id: 8f381419-802a-d704-e146-9fe6a69db23e
            type: block
            subtype: false
            title: Untitled
            attributes:
              size: 30
            children:
              -
                id: f02d567e-1159-8832-2ef9-9efb0908dd3b
                type: spacer
                subtype: false
                title: Spacer
                attributes:
                  enabled: 1
                children: {  }
          -
            id: e96a94bb-4b6f-6afc-33a4-33f45c6fa0c8
            type: block
            subtype: false
            title: Untitled
            attributes:
              size: 30
            children:
              -
                id: f15c8b44-8259-9d23-3a41-25f083c2d839
                type: particle
                subtype: branding
                title: Branding
                attributes:
                  enabled: 1
                children: {  }
  -
    id: 86f198de-5344-f386-9c3a-cc5be5f99031
    type: offcanvas
    subtype: false
    title: Offcanvas
    attributes:
      name: 'Offcanvas Section'
      boxed: 0
    children:
      -
        id: d4c28a40-c492-6b91-d1f7-860cc36c1073
        type: grid
        subtype: false
        title: Untitled
        attributes: {  }
        children:
          -
            id: a1f3266b-feda-cab1-c116-59fa53672890
            type: block
            subtype: false
            title: Untitled
            attributes:
              size: 100
            children:
              -
                id: b5255e43-2ef1-784d-3622-b33a5ac24bfc
                type: particle
                subtype: mobile-menu
                title: Mobile-menu
                attributes:
                  enabled: 1
                children: {  }
  -
    id: 225f43f9-7b98-bdd7-84d3-7c231eb26aae
    type: atoms
    subtype: false
    title: Atoms
    attributes:
      name: 'Atoms Section'
      boxed: 0
    children:
      -
        id: 779dff39-860d-4b9b-8ed7-6f1898bf5e5c
        type: grid
        subtype: false
        title: Untitled
        attributes: {  }
        children: {  }
